---
title: "CaseStudy2_final_mmastrangeli"
author: "Mark Mastrangeli"
date: "12/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(base)
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(knitr)
library(mlr)
library(caret)
#colnames(read.csv("CaseStudy2-data.csv", header = TRUE))
```

## R Markdown

```{r Import}
#Collecting and setting up persistent variables
dfTrainImport <- read_csv("CaseStudy2-data.csv")
dfValImport <- read_csv("CaseStudy2Validation.csv")
dfTrainColumns <- colnames(dfTrainImport)
dfTrainColumns
dfValColumns <- colnames(dfValImport)
dfTrainImportSum <- summary(dfTrainImport)
dfValImportSum <- summary(dfValImport)
str(dfTrainImport)
str(dfValImport)


dfValKey <- cbind2(dfValImport$ID, dfValImport$Attrition)

#Function to convert monthly income to annual income 
MonthToYear <- function(x){
  x = x * 12
}

dfTrain.1 <- dfTrainImport
head(dfTrain.1)

```
```{r Transform}
#filter() examples
#filter(starwars, species == "Human")
#filter(starwars, mass > 1000)

# Multiple criteria
#filter(starwars, hair_color == "none" & eye_color == "black")
#filter(starwars, hair_color == "none" | eye_color == "black")

# Multiple arguments are equivalent to and
#filter(starwars, hair_color == "none", eye_color == "black")

#filter_all() examples
# While filter() accepts expressions with specific variables, the
# scoped filter verbs take an expression with the pronoun `.` and
# replicate it over all variables. This expression should be quoted
# with all_vars() or any_vars():
#all_vars(is.na(.))
#any_vars(is.na(.))


# You can take the intersection of the replicated expressions:
#filter_all(mtcars, all_vars(. > 150))
# Or the union:
#filter_all(mtcars, any_vars(. > 150))

# You can vary the selection of columns on which to apply the
# predicate. filter_at() takes a vars() specification:
#filter_at(mtcars, vars(starts_with("d")), any_vars((. %% 2) == 0))

# And filter_if() selects variables with a predicate function:
#filter_if(mtcars, ~ all(floor(.) == .), all_vars(. != 0))


#cleaning and munging data, persistence, statistics
dfTrain <- as.data.frame(dfTrainImport)
#dfTrain Attrition Rate for Sample size tally(dfTrain$Attrition == "Yes")/tally(rows(dfTrain))
factor(dfTrain$Attrition)

#Attrition Rate in dfTrain Sample Set
dfTrainAttrition = filter(dfTrain, Attrition == "Yes")
dfTrainAttrRate = (count(dfTrainAttrition))/1170
colnames(dfTrainAttrRate) <- c("dfTrainAttritionRate")
dfTrainAttrRate <- as.numeric(dfTrainAttrRate)
print(dfTrainAttritionRate)
dfTrainAttrRate

#Attrition Rate Per Variable Factor Level

#Attrition Rate by Job Satisfaction

#dfTrain.var <- c(colnames(dfTrain$4)
                
#variable.names(dfTrain)

#dfTrain.var = filter(dfTrain, dfTrain.var >= 0 )

#Factor Level 1
dfTrain.JobSatisfactionL1 = filter(dfTrain, Attrition == "Yes" & JobSatisfaction == 1)
#Job Satisfaction Level 1 Attrition Rate
dfTrain.JobSatAttrRateL1 = count(dfTrain.JobSatisfactionL1)/1170
#Factor Level 2
dfTrain.JobSatisfactionL2 = filter(dfTrain, Attrition == "Yes" & JobSatisfaction == 2)
dfTrain.JobSatAttrRateL2 = count(dfTrain.JobSatisfactionL2)/1170
#Factor Level 3
dfTrain.JobSatisfactionL3 = filter(dfTrain, Attrition == "Yes" & JobSatisfaction == 3)
dfTrain.JobSatAttrRateL3 = count(dfTrain.JobSatisfactionL3)/1170
#Factor Level 4
dfTrain.JobSatisfactionL4 = filter(dfTrain, Attrition == "Yes" & JobSatisfaction == 4)
dfTrain.JobSatAttrRateL4 = count(dfTrain.JobSatisfactionL4)/1170

#Validation against total number of Yes Attrition in dfTrain
sum(count(dfTrain.JobSatisfactionAttr1), count(dfTrain.JobSatisfactionAttr2), count(dfTrain.JobSatisfactionAttr3), count(dfTrain.JobSatisfactionAttr4))

max(dfTrain.JobSatAttrRateL1, dfTrain.JobSatAttrRateL2, dfTrain.JobSatAttrRateL3, dfTrain.JobSatAttrRateL4)


VariableAttrRateL1 <- dfTrain.JobSatAttrRateL1
VariableAttrRateL2 <- dfTrain.JobSatAttrRateL2
VariableAttrRateL3 <- dfTrain.JobSatAttrRateL3
VariableAttrRateL4 <- dfTrain.JobSatAttrRateL4

VariableSatRates <- data.frame(c(VariableAttrRateL1, VariableAttrRateL2, VariableAttrRateL3, VariableAttrRateL4))
colnames(VariableSatRates) <- c("Level 1 Attr Rate", "Level 2 Attr Rate", "Level 3 Attr Rate", "Level 4 Attr Rate")
VariableSatRates


dfTrainAttritionRate = (count(dfTrainAttrition))/1170
colnames(dfTrainAttritionRate) <- c("dfTrainAttritionRate")
dfTrainJobSatisfactionAttr <- 
  
print(dfTrainAttritionRate)

AttrFunc <- function(x,y){
  
  
}

#for Example
#for(i in 1:5) print(1:i)
#for(n in c(2,5,10,20,50)) {
 #  x <- stats::rnorm(n)
  # cat(n, ": ", sum(x^2), "\n", sep = "")
#}
#f <- factor(sample(letters[1:5], 10, replace = TRUE))
#for(i in unique(f)) print(i)

for(n in count(dfTrainColumns)){
  print(dfTrainColumns[n,])
}

```
```{r Visualize}
#Combining visualization and data sense to explor data
#Understanding biases in data
dfTrainColumns
#What is the attrition rate for the categorical or factor variables: Age, BusinessTravel, DailyRate, Department, DistancefromHome, Education, EducationField, EnvironmentalSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, NumCompaniesWorked, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager


```
```{r Model}
#Finding patterns, building models, writing algorithms
```
