library(base)
library(XML)
library(dplyr)
library(stats)
library(plyr)
library(tidyr)
library(stringi)
library(rvest)
library(ggplot2)
library(RCurl)
library(git2r)

setwd("/Users/mmastran/SMU/MSDS/github/MSDS/Unit06HW/N-MHSS-2015-DS0001-bndl-data-r/N-MHSS-2015-DS0001-data/")
load("N-MHSS-2015-DS0001-data-r.rda", envir = parent.frame(), verbose = FALSE)